### ISSUE TITLE
Cannot compile source

### ISSUE THREAD

**Issue by gcapnias** [eellak/scriptum#4]
Σε προσπάθεια να κάνω compile το project, μου βγάζει σφάλματα και ότι λείπουν αρχεία.

Έχει δοκιμαστεί ο κώδικας αν κάνει compile; Υπάρχουν κάπου οδηγίες πως γίνεται compile; Στην παλιά έκδοση υπήρχε αρχείο .sql για να φτιαχτεί η βάση. Στην έκδοση rescriptum δεν υπάρχει, όπως έχει φύγει και ο κατάλογος με το documentation του σχήματος της βάσης.

**Comment by el95149** [comment]
@gcapnias Παρακαλώ δείτε το #5 .
